# Generated by Django 5.0.6 on 2024-07-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
